# Options
pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password
pulp_install_plugins:
  # pulp-ansible:
  #   source_dir: "/home/vagrant/devel/pulp_ansible"
  pulp-certguard:
    source_dir: "git+https://github.com/pulp/pulp-certguard.git#egg=pulp-certguard"
  # pulp-cookbook:
  #   source_dir: "/home/vagrant/devel/pulp_cookbook"
  # pulp-deb:
  #   source_dir: "/home/vagrant/devel/pulp_deb"
  pulp-docker:
    source_dir: "git+https://github.com/pulp/pulp_docker.git#egg=pulp-docker"
  # pulp-gem:
  #   source_dir: "/home/vagrant/devel/pulp_gem"
  # pulp-maven:
  #   source_dir: "/home/vagrant/devel/pulp_maven"
  # pulp-python:
  #   source_dir: "/home/vagrant/devel/pulp_python"
  pulp-rpm:
    source_dir: "git+https://github.com/pulp/pulp_rpm.git#egg=pulp-rpm"
    prereq_role: "pulp.pulp_rpm_prerequisites"
  pulp-file:
    source_dir: "git+https://github.com/pulp/pulp_file.git#egg=pulp-file"

# Vagrant source install Required
pulp_user: "vagrant"
developer_user: "vagrant"
developer_user_home: "/home/vagrant"
pulp_source_dir: "/home/vagrant/devel/pulpcore"
# Uncomment if using pulp-rpm
pulp_use_system_wide_pkgs: true
pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
